import { Injectable, ForbiddenException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

// MerchantPlan is generated by Prisma — defined here as a fallback type
type MerchantPlan = 'FREE' | 'PRO' | 'GRANDFATHERED';

/** Plan limits for FREE tier */
const FREE_LIMITS = {
  maxActiveServices: 2,
  maxBookingsPerMonth: 50,
};

@Injectable()
export class PlanService {
  constructor(private readonly prisma: PrismaService) {}

  /** Returns true if merchant is on PRO or GRANDFATHERED plan */
  isPro(plan: MerchantPlan): boolean {
    return plan === 'PRO' || plan === 'GRANDFATHERED';
  }

  /** Check if merchant can create another service */
  async checkServiceLimit(merchantId: string, plan: MerchantPlan): Promise<void> {
    if (this.isPro(plan)) return;

    const count = await this.prisma.service.count({
      where: { merchantId, isActive: true },
    });

    if (count >= FREE_LIMITS.maxActiveServices) {
      throw new ForbiddenException(
        `Free plan is limited to ${FREE_LIMITS.maxActiveServices} active services. Upgrade to Pro for unlimited services.`,
      );
    }
  }

  /** Check if merchant can create another booking this month */
  async checkBookingLimit(merchantId: string, plan: MerchantPlan): Promise<void> {
    if (this.isPro(plan)) return;

    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

    const count = await this.prisma.booking.count({
      where: {
        merchantId,
        createdAt: { gte: startOfMonth, lte: endOfMonth },
      },
    });

    if (count >= FREE_LIMITS.maxBookingsPerMonth) {
      throw new ForbiddenException(
        `Free plan is limited to ${FREE_LIMITS.maxBookingsPerMonth} bookings per month. Upgrade to Pro for unlimited bookings.`,
      );
    }
  }

  /** Get current booking count for this month (for frontend warning) */
  async getMonthlyBookingCount(merchantId: string): Promise<{ count: number; limit: number }> {
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

    const count = await this.prisma.booking.count({
      where: {
        merchantId,
        createdAt: { gte: startOfMonth, lte: endOfMonth },
      },
    });

    return { count, limit: FREE_LIMITS.maxBookingsPerMonth };
  }
}
